runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --timeout 100 main:app

runtime_config:
  python_version: 3

service: quora-classifier

skip_files:
  - ^\..*$

env_variables:
  GCS_BUCKET: "green-wares-224816"
  GCS_MODEL_BLOB: "model.joblib"
  GCS_DATA_BLOB: "train.csv"

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10